apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: proxy:v1
        ports:
        - containerPort: 30080
        - containerPort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-lookup
  labels:
    app: proxy-lookup
spec:
  type: NodePort
  ports:
  - name: proxy-register
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-register
  labels:
    app: proxy-register
spec:
  type: NodePort
  ports:
  - name: proxy-register
    port: 81
    targetPort: 81
    nodePort: 30081
  selector:
    app: proxy
