apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: gcr.io/continuum-compute/proxy:v1
        ports:
        - containerPort: 80
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-lookup
  labels:
    app: proxy-lookup
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-register
  labels:
    app: proxy-register
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 81
  selector:
    app: proxy
