apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/computetesting/scipy-app:v1
        ports:
        - containerPort: 8080
        env:
        - name: KUBERNETES_API
          value:
        - name: KUBERNETES_USERNAME
          value:
        - name: KUBERNETES_PASSWORD
          value:
---
apiVersion: v1
kind: Service
metadata:
  name: app-server
  labels:
    app: app-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app
